chromosome_type: "cartesian"

pick_pose:
  id        : "pick"
  base      : [0.7 , 0, 0.6, 0, 0, 0]                       # base pose
  l_bound   : [-0.3,-0.3, -0.1, 0, 0, -0.3]              # min delta
  u_bound   : [0.3 , 0.3, 0.1, 0, 0,  0.3]               # max delta
  linspace  : [120,120,1,1,1,50]                        # mesh
  offset    : [0, 0, 0, 0, 0, 0]                          # offset rispetto origine della mesh
  ee_offset : [-0.12, 0, 0, 0, 1.5707, 0]                   # pose of the end effector wrt component pose

place_pose:
  id        : "place"
  base      : [0, 0.7, 0.25, 0, 1.5707, 1.5707]
  l_bound   : [-0.3, -0.3, -0.1, 0, 0, -0.1]
  u_bound   : [0.3,   0.3,  0.1, 0, 0, 0.1]
  linspace  : [120,120,1,1,1,50]
  offset    : [0, 0, 0, 0, 0, 0]
  ee_offset : [-0.42,0,0,0,1.5707,0]
