chromosome_type: "cartesian"                  # type pf the chromosome - cartesian and spherical implemented

pick_pose:
  id        : "pick"                          # name of the pick pose
  base      : [0.7 , 0, 0.6, 0, 0, 0]         # base pose
  l_bound   : [-0.3,-0.3, -0.1, 0, 0, -0.3]   # search space lower bound
  u_bound   : [0.3 , 0.3, 0.1, 0, 0,  0.3]    # search space upwer bound
  linspace  : [120,120,1,1,1,50]              # search sapce discretization
  offset    : [0, 0, 0, 0, 0, 0]              # offset wrt mesh origin
  ee_offset : [-0.02, 0, 0, 0, 0, 0]          # goal pose of the end effector wrt component pose

place_pose:
  id        : "place"
  base      : [-0.7, 0.0, 0.25, 0, 1.5707, 3.1415]
  l_bound   : [-0.4, -0.4, -0.1, 0, 0, -0.1]
  u_bound   : [0.4,   0.4,  0.1, 0, 0, 0.1]
  linspace  : [120,120,1,1,1,50]
  offset    : [0, 0, 0, 0, 0, 0]
  ee_offset : [-0.29,0,0,0,0,0]
