joint_home  : [       0, -1.5707,       0,       0,      0,       0 ] # joint values of the home position
lower_bounds: [ -3.1416, -3.1416, -3.1416, -3.1416,-3.1416, -3.1416 ] # lower joints limits
upper_bounds: [  3.1416,  3.1416,  3.1416,  3.1416, 3.1416,  3.1416 ] # upper joints limits

pick:
  seed_target_joints: [-2.9, -1.7, -1.7, 0.3, 1.3, 1.6]               # joint values used as seed to find the joint configuration relative to the pick pose
place:
  seed_target_joints: [0.25, -1.7, -1.25, -1.5, 1.5, -2.7]            # joint values used as seed to find the joint configuration relative to the place pose


