chromosome_type: "spherical"

pick_pose:
  id        : "pick"
  base      : [  0,    0,    0,  0,    0,    0]
  l_bound   : [0.6, -0.5,  0.3,  0, -0.1,  0.5]               # (rho, theta, phi) -> x,y,z; delta_theta -> orientazione pannello
  u_bound   : [0.9,  0.5,  0.7,  0,  0.1, -0.5]
  linspace  : [10,    30,   30, 20,   20,   20]
  offset    : [0, 0, 0, 0, 0, 0]
  ee_offset : [ -0.02, 0, 0, 0, 0, 0 ]

place_pose:
  id      : "place"
  base    : [  0,  0, 0.25, 0, 1.5707, 0 ]
  l_bound : [ 0.4, 1.5707, 0,  0,      0,  -0.2]
  u_bound : [ 0.9, 4.6817, 0,  0,      0,     0.2]
  linspace: [ 10,  30,30, 20,     20,      20]
  offset  : [ 0, 0, 0, 0, 0, 0 ]
  ee_offset : [-0.29,0,0,0,0, 0 ]

